<?php
/**
 * Plugin Name: AITU Login Slug
 * Description: Moves the public WordPress login screen to /aitu-login.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! defined( 'AITU_LOGIN_SLUG' ) ) {
	define( 'AITU_LOGIN_SLUG', 'aitu-login' );
}

/**
 * Get custom login path.
 *
 * @return string
 */
function aitu_login_slug_path() {
	return '/' . trim( AITU_LOGIN_SLUG, '/' );
}

/**
 * Get custom login URL.
 *
 * @param array<string, string> $args Query args.
 * @return string
 */
function aitu_login_slug_url( $args = array() ) {
	$url = home_url( aitu_login_slug_path() . '/', 'login' );
	if ( ! empty( $args ) ) {
		$url = add_query_arg( $args, $url );
	}

	return $url;
}

/**
 * Normalize a request path for comparison.
 *
 * @param string $path Raw path.
 * @return string
 */
function aitu_login_normalize_path( $path ) {
	$normalized = '/' . ltrim( (string) $path, '/' );
	$normalized = untrailingslashit( $normalized );
	return '' === $normalized ? '/' : $normalized;
}

/**
 * Get current request path.
 *
 * @return string
 */
function aitu_login_current_request_path() {
	$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? (string) wp_unslash( $_SERVER['REQUEST_URI'] ) : '/';
	$path        = (string) wp_parse_url( $request_uri, PHP_URL_PATH );

	return aitu_login_normalize_path( $path );
}

/**
 * Check if current request targets the custom login slug.
 *
 * @return bool
 */
function aitu_login_is_custom_login_request() {
	return aitu_login_current_request_path() === aitu_login_normalize_path( aitu_login_slug_path() );
}

/**
 * Check if current request targets wp-login.php directly.
 *
 * @return bool
 */
function aitu_login_is_default_login_request() {
	return (bool) preg_match( '#/wp-login\.php$#', aitu_login_current_request_path() );
}

/**
 * Get current request query args.
 *
 * @return array<string, string>
 */
function aitu_login_current_query_args() {
	$request_uri = isset( $_SERVER['REQUEST_URI'] ) ? (string) wp_unslash( $_SERVER['REQUEST_URI'] ) : '';
	$query       = (string) wp_parse_url( $request_uri, PHP_URL_QUERY );
	$args        = array();

	if ( '' !== $query ) {
		parse_str( $query, $args );
	}

	return array_filter(
		$args,
		static function ( $value ) {
			return null !== $value && '' !== $value;
		}
	);
}

/**
 * Replace wp-login.php in URL with the custom login slug.
 *
 * @param string $url URL to rewrite.
 * @return string
 */
function aitu_login_rewrite_login_url( $url ) {
	$url = (string) $url;
	if ( '' === $url || false === strpos( $url, 'wp-login.php' ) ) {
		return $url;
	}

	$parts = wp_parse_url( $url );
	if ( ! is_array( $parts ) ) {
		return $url;
	}

	$args = array();
	if ( ! empty( $parts['query'] ) ) {
		parse_str( (string) $parts['query'], $args );
	}

	return aitu_login_slug_url( $args );
}

/**
 * Rewrite login URLs generated by WordPress core during login bootstrap.
 *
 * @param string      $url URL.
 * @param string      $path Path.
 * @param string|null $scheme Scheme.
 * @param int|null    $blog_id Blog ID.
 * @return string
 */
function aitu_login_filter_site_url( $url, $path, $scheme, $blog_id ) {
	unset( $blog_id );

	$path = (string) $path;
	if ( false === strpos( $path, 'wp-login.php' ) && false === strpos( (string) $url, 'wp-login.php' ) ) {
		return $url;
	}

	if ( in_array( (string) $scheme, array( 'login', 'login_post', 'logout', 'lostpassword' ), true ) || false !== strpos( $path, 'wp-login.php' ) ) {
		return aitu_login_rewrite_login_url( $url );
	}

	return $url;
}

/**
 * Rewrite network login URLs generated by WordPress core during login bootstrap.
 *
 * @param string      $url URL.
 * @param string      $path Path.
 * @param string|null $scheme Scheme.
 * @return string
 */
function aitu_login_filter_network_site_url( $url, $path, $scheme ) {
	$path = (string) $path;
	if ( false === strpos( $path, 'wp-login.php' ) && false === strpos( (string) $url, 'wp-login.php' ) ) {
		return $url;
	}

	if ( in_array( (string) $scheme, array( 'login', 'login_post', 'logout', 'lostpassword' ), true ) || false !== strpos( $path, 'wp-login.php' ) ) {
		return aitu_login_rewrite_login_url( $url );
	}

	return $url;
}

/**
 * Rewrite redirect targets pointing to wp-login.php.
 *
 * @param string $location Redirect target.
 * @return string
 */
function aitu_login_filter_wp_redirect( $location ) {
	return aitu_login_rewrite_login_url( $location );
}
add_filter( 'wp_redirect', 'aitu_login_filter_wp_redirect', 10, 1 );

/**
 * Override login URL helper.
 *
 * @param string $login_url Login URL.
 * @param string $redirect Redirect target.
 * @param bool   $force_reauth Force reauth.
 * @return string
 */
function aitu_login_filter_login_url( $login_url, $redirect, $force_reauth ) {
	$args = array();
	if ( '' !== (string) $redirect ) {
		$args['redirect_to'] = $redirect;
	}
	if ( $force_reauth ) {
		$args['reauth'] = '1';
	}

	return aitu_login_slug_url( $args );
}
add_filter( 'login_url', 'aitu_login_filter_login_url', 10, 3 );

/**
 * Override logout URL helper.
 *
 * @param string $logout_url Logout URL.
 * @param string $redirect Redirect target.
 * @return string
 */
function aitu_login_filter_logout_url( $logout_url, $redirect ) {
	unset( $redirect );
	return aitu_login_rewrite_login_url( $logout_url );
}
add_filter( 'logout_url', 'aitu_login_filter_logout_url', 10, 2 );

/**
 * Override lost password URL helper.
 *
 * @param string $lostpassword_url Lost password URL.
 * @param string $redirect Redirect target.
 * @return string
 */
function aitu_login_filter_lostpassword_url( $lostpassword_url, $redirect ) {
	$args = array( 'action' => 'lostpassword' );
	if ( '' !== (string) $redirect ) {
		$args['redirect_to'] = $redirect;
	}

	return aitu_login_slug_url( $args );
}
add_filter( 'lostpassword_url', 'aitu_login_filter_lostpassword_url', 10, 2 );

/**
 * Override register URL helper.
 *
 * @param string $register_url Register URL.
 * @return string
 */
function aitu_login_filter_register_url( $register_url ) {
	unset( $register_url );
	return aitu_login_slug_url( array( 'action' => 'register' ) );
}
add_filter( 'register_url', 'aitu_login_filter_register_url', 10, 1 );

/**
 * Boot the custom login endpoint and block direct wp-login.php access.
 *
 * @return void
 */
function aitu_login_bootstrap() {
	$request_path = aitu_login_current_request_path();
	$is_default   = (bool) preg_match( '#/wp-login\.php$#', $request_path );
	$is_custom    = $request_path === aitu_login_normalize_path( aitu_login_slug_path() );
	$is_post      = 'POST' === strtoupper( isset( $_SERVER['REQUEST_METHOD'] ) ? (string) $_SERVER['REQUEST_METHOD'] : 'GET' );

	if ( is_admin() && ! $is_default ) {
		return;
	}

	if ( wp_doing_ajax() || wp_doing_cron() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) {
		return;
	}

	if ( $is_default && ! $is_post ) {
		wp_safe_redirect( aitu_login_slug_url( aitu_login_current_query_args() ), 302 );
		exit;
	}

	if ( ! $is_custom && ! $is_default ) {
		return;
	}

	global $pagenow;
	$pagenow = 'wp-login.php';

	if ( ! defined( 'WP_USE_THEMES' ) ) {
		define( 'WP_USE_THEMES', false );
	}

	$user_login = '';
	$error      = '';

	add_filter( 'site_url', 'aitu_login_filter_site_url', 10, 4 );
	add_filter( 'network_site_url', 'aitu_login_filter_network_site_url', 10, 3 );

	require_once ABSPATH . 'wp-login.php';
	exit;
}
add_action( 'init', 'aitu_login_bootstrap', 0 );
